import React, { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import man1 from "../../../assets/man1.png";
import man2 from "../../../assets/man2.png";
import man3 from "../../../assets/man3.png";
import man4 from "../../../assets/man4.png";
import man5 from "../../../assets/man5.png";
import man6 from "../../../assets/man6.png";
import man7 from "../../../assets/man7.png";
import man8 from "../../../assets/man8.png";
import ManPicCard from "../../Card/manPicCard";

function MembersSec({ heading, subheading, layout = "slider", scrollType = "continuous", headingLayout = "column" }) {
    const pics = [
        {
            img: man1, text: "Muhammadjon Tinishboyev", dob: "1879-1939-yillar", about:
                "Muhammadjon Tinishboyev [Muxamedjan Tinishpayev]– davlat va jamoat arbobi, tarixchi olim. 1879-yil 12-mayda Yettisuv viloyati Lepsinsk uyezdi Sadir volostining Echkiolmas togʻi etagida tugʻilgan. Millati – qozoq. U 1889 – 1900-yillarda Verniy erkaklar gimnaziyasi, 1900 – 1906-yillarda Sankt-Peterburg Imperatorlik instituti – Aleksandr I nomidagi temir yoʻl transporti injenerlar institutida oʻqidi. 1907-yili II chaqiriq Rossiya Davlat dumasi deputati qilib saylandi. 1917-yil aprelda tuzilgan Muvaqqat hukumatning Turkiston komiteti aʼzosi. Ayni paytda Muvaqqat hukumatning Yettisuv viloyati komissari[2]. Qoʻqonda Turkiston Muxtoriyati hukumati 1917-yil 27-noyabrda tashkil topgach, hukumatning Bosh vaziri (1917-yil noyabr – dekabr) va ichki ishlar vaziri (1917-yil noyabr – 1918-yil fevral). 1917-yil 5 – 13-dekabrda Orenburgda oʻtkazilgan II Butunqozoq syezdida qatnashdi. Bu syezdda Alixon Bukeyxonov (1866 – 1937) boshchiligida Alash avtonomiyasi [Alash Oʻrda hukumati] tashkil topdi. U Alash Oʻrda hukumatida ichki ishlar vaziri (1917-yil dekabr – 1920-yil mart) va keyinchalik Bosh vazir oʻrinbosari lavozimlarida ishladi.\n" +
                "M.Tinishboyev keyinchalik Turkiston ASSR va Qozogʻiston ASSRda turli lavozimlarda faoliyat koʻrsatdi. Turkiy xalqlar tarixi va etnografiyasiga oid turli asarlar yozgan hamda ular rus tilida Toshkentda nashr qilingan.\n" +
                "Sovet hokimiyati tomonidan M. Tinishboyev birinchi marta 1930-yil 3-avgustda qamoqqa olindi va besh yilga RSFSRning Markaziy qoratuproq hududi (hozirgi Voronej oblasti)ga surgun qilindi (1930 – 1935). Keyinchalik Toshkentda NKVD tomonidan 1937-yil 21-noyabrda qayta qamoqqa olindi hamda Toshkent turmasidagi kasalxonada u 1939-yil 3-iyulda vafot etdi.\n" +
                "1970-yil 27-fevralda Oʻzbekiston SSR Ministrlar Soveti huzuridagi KGB tergov boʻlimi tomonidan M.Tinishboyevga nisbatan jinoiy ish qayta koʻrib chiqilib, u reabilitatsiya qilindi.\n" + "M.Tinishboyevning tanlangan asarlari va boshqa kitoblari Almatida 1991-yildan keyin nashr etildi. SSSR tarqalgach, Qozogʻistonda uning xotirasi sharafiga koʻplab haykallari oʻrnatildi. Qozogʻistonda maxsus medal chiqarilgan."

        },
        {
            img: man2, text: "Abdurahmon O‘razboyev ", dob: "1888-1937-yillar", about: "Abdurahmon O‘razboyev -  taniqli davlat va jamoat arbobi.1888 yilda Yangi Marg‘ilon (hozirgi Farg‘ona) shahrida amaldor oilasida tug‘ilgan. Abdurahmonbek ota tomondan xuddi Mustafo Cho‘qay ajdodlari singari qozoqlarning qipchoq urug‘iga borib taqaladi. Otasi – Muhammad O‘razayev (1898 yil 10 mayda vafot etgan) O‘rta juzdagi aslzodalardan biri bo‘lib, 2-Orenburg kadet korpusini tugatgan hamda Marg‘ilon uyezdi boshqarmasida tarjimon va kotib bo‘lib ishlagan. Onasi – Niyozjon Bibixonim Farg‘ona viloyati Yangi Marg‘ilon uyezdi Avval qishlog‘ida tug‘ilgan o‘zbek ayoli bo‘lib, u erining vafotidan so‘ng o‘qituvchilik qilgan. Yosh Abdurahmonbek tarbiyasida onasining xizmati katta edi. \n" +
                "A.O‘razayev Skobelev gimnaziyasi (1910) va Moskva universitetining yuridik fakultetini (1915) tugatgan. Advokat yordamchisi lavozimida ishlagan. Farg‘ona saylov okrugidan Butunrossiya Ta’sis Majlisi a’zosi (1917) qilib saylandi. Turkiston Muxtoriyati hukumati 1917 yil noyabrda tashkil qilingach, u ichki ishlar vazirining o‘rinbosari hamda Milliy Majlis a’zosi bo‘ldi. So‘ngra ichki ishlar vaziri lavozimida faoliyat ko‘rsatdi. Eserlar partiyasiga xayrixoh bo‘lgan. Muxtoriyat hukumati bolsheviklar tomonidan ag‘darilgach, 1918 yil fevral oyi oxirida A. O‘razayev bolsheviklar qo‘liga tushib qolgan. U 1918 yil may oyida dastlab amnistiya qilindi hamda sovet hokimiyati idoralarida turli lavozimlarda ishladi. A.O‘razayev keyinchalik Sibirga surgun qilindi. U yerda sil kasali bilan qattiq og‘rib qolgach, Toshkentdagi qarindoshlari (singlisi) oilasiga qaytishga ruxsat berildi. U bo‘lg‘usi akademik bo‘lgan kuyovi Qori Niyoziy xonadonida yashadi. Toshkentda bir muddat istiqomat qilgach, taxminan 1937 yilda og‘ir kasallik natijasida vafot etdi.\n" + "Abdurahmonbek O‘razayevning ikki nafardan akasi va singlisi bo‘lgan. Uning shaxsiy hayoti haqida yetarlicha ma’lumotlar saqlanib qolmagan. A.O‘razayevning singlisi: Oyshaxonim O‘razayeva (1897 yil 2 sentyabr – 1988 yil 31 yanvar) onasi singari sovet maktablarida ishlagan. Turkistonda dastlabki ayol o‘qituvchilardan biri bo‘lgan. U Skobelev (hozirgi Farg‘ona) shahridagi ayollar gimnaziyasini tugatib, Namangandagi rus-tuzem maktabida rus tilidan dars bergan. So‘ngra Skobelevdagi sovet maktabida faoliyat ko‘rsatdi. U keyinchalik mashhur matematik olim bo‘lib yetishgan O‘zbekiston fan arbobi (1939), O‘zbekiston Fanlar akademiyasi akademigi va birinchi prezidenti (1943-1947), fizika-matematika fanlari doktori (1939), professor, Sosialistik Mehnat Qahramoni (1967) bo‘lgan.\n" +

                "Toshmuhammad Niyozovich Qori-Niyoziy (1897, Xo‘jand – 1970, Toshkent)ga turmushga chiqqan. T.N.Qori-Niyoziy O‘rta Osiyo davlat universitetini tugatgach (1929), shu universitet rektori (1931-1933), O‘zbekiston SSR Maorif xalq komissari va ayni paytda O‘zbekiston XKS huzuridagi Fan qo‘mitasi Prezidiumi raisi (1937-1938), O‘zbekiston SSR XKS raisi o‘rinbosari (1939-1943), SSSR FA  O‘zbekiston filiali Prezidiumi raisi (1940-1943) hamda boshqa mas’ul lavozimlarda faoliyat ko‘rsatdi. Shu narsa xarakterli holki, sovet davrida o‘z tarjimai holini ancha o‘zgartirgan er-xotin Toshmuhammad va Oyshaxonim ikkalasi go‘yoki ham bir kunda, ham bir yilda – 1897 yil 2 sentyabrda biri Xo‘jandda, ikkinchisi Skobelev shahrida tug‘ilganligi to‘g‘risida rasmiy hujjatlarda yozishgan. Qori-Niyoziy sovet rejimi davrida, bir tomondan, O‘zbekistonda sovet madaniyati va ilm-fanini rivojlantirishga katta hissa qo‘shgan bo‘lsa, ikkinchi tomondan, o‘zbek xalqi ma’naviyati va milliy madaniyatga qaqshatqich va ayovsiz zarba bergan."
        },

        {
            img: man8, text: "Hidoyatbek Yurali Agayev", dob: "Tug‘ilgan yillari nom’alum", about: "Hidoyatbek Yurg‘uli Ag‘ayev – davlat va jamoat arbobi. Farg‘ona vodiysida XIX asr so‘nggi choragida tug‘ilgan. U o‘lkada taniqli agronom olim sifatida mashhur edi. Turkiston Muxtoriyati hukumatida yer va suv boyliklari vaziri lavozimida faoliyat ko‘rsatgan. Turkiston Milliy Majlisi a’zosi sifatida ham samarali ish olib borgan.\n" +
                "Qo‘qon shahri 1918 yil fevralda bolsheviklar tomonidan o‘qqa tutilgan paytda Bosh vazir Mustafo Cho‘qay yonida Hidoyatbek Yurali Agayev ham bo‘lgan. Biroq Qo‘qonda bolsheviklarning harbiy kuchlariga qarshi bo‘lgan janglarning birida u halok bo‘ladi.\n" +
                "H.Agayevning rafiqasi: Jozefina Stanislavovna Yurguli-Aga (qizlik familiyasi Trushkovskaya) Peterburg patriot institutini tugatgan."
        },
        {
            img: man3, text: "Solomon Geresfeld", dob: "1881-1937-yillar", about: "Turkistondagi yirik sarmoyadorlardan biri, advokat va jurnalist. Sionistlar komitetining O‘rta Osiyo rayoni raisi. 1881 yil 27 noyabrda Odessada tug‘ilgan. Millati – buxoro yahudiylaridan. Bern universiteti (Shveysariya) yuridik fakultetining erkin tinglovchisi (1902 yildan). Rossiyaga qaytgach, Odessa yunkerlik bilim yurtiga imtihon topshirib, Samarqanddagi 6-Turkiston batalonida harbiy xizmatni boshlagan. 1904 – 1906 yillarda rus tilida “Samarkand” gazetasini chiqargan. Odessadagi Novorossiysk universiteti yuridik fakulteti 2-kurs talabaligiga qabul qilingan (1907). Odessa sionistlar komitetiga 1908 yil sentyabrda saylangan, “Odesskoye slovo” gazetasini chiqargan. 1913 yil mayda universitetni tugatib, Samarqandga qaytgan. Samarqand shahar Dumasida yahudiylar komiteti raisi. Samarqand shahar Dumasi a’zosi (1917).\n" +
                "Turkiston Muxtoriyati hukumatining birinchi tarkibida tub xalqlardan bo‘lmagan yagona nomzod sifatida kirib, moliya vaziri bo‘lgan. Milliy Majlis a’zosi (1917 yil noyabr – 1918 yil fevral). Keyinchalik moliya vaziri lavozimini Islom Shoaxmedovga topshirgan. Muxtoriyat hukumati ag‘darilganda qizil gvardiyachilar tomonidan Qo‘qonda 1918 yil 20 fevralda qo‘lga olingan va otib tashlangan. U O‘rta Osiyo temir yo‘lining Melnikovo stansiyasi (hozirgi Konibodom)da dafn etilgan. Mustafo Cho‘qayning yozishicha, “Harsfeld Samarqandda bolsheviklar qo‘liga tushib qolgan edi”.\n" +
                "Buxoro yahudiylari talabi bilan S.Gersfeldning jasadi 1918 yil 16 aprelda eksgumasiya qilinib, yahudiylar jamoasi tomonidan uning jasadi Samarqanddagi yahudiylar qabristonida qayta dafn etilgan. Halok bo‘lgan paytda S.A. Gersfeld hali 37 yoshga ham to‘lmagan edi."
        },
        {
            img: man4, text: "Mustafo Cho‘qay", dob: "1890-1937-yillar", about:
                " Mustafo Cho‘qay – taniqli davlat va jamoat arbobi hamda Turkiston xalqlari mustaqilligi uchun izchil kurashch.\n" +
                "1890 yil 25 dekabrda [yangi hisob bilan 1891 yil 7 yanvarda] Sirdaryo oblasti Perovsk uyezdi Jopek volostidagi Avliyotarang‘il ovulida (ba’zi manbalarda yozilishicha, Narshoki qishlovida) tug‘ilgan. Otasi Cho‘kaybey To‘rg‘ay dodxoh o‘g‘li bo‘lis (volost) boshlig‘i, qozoqlarning qipchoq urug‘i aslzodalaridan bo‘lgan, onasining ajdodlari Xiva xonlariga borib taqalgan. Mustafo Cho‘qay tarjimai holida o‘zini qipchoq deb hisoblagan.\n" +

                "Mustafo Cho‘qay boshlang‘ich ma’lumotni Oqmachitda olgach, Toshkentdagi erkaklar gimnaziyasida o‘qidi(1902 – 1910).Sankt - Peterburg universitetining yuridik fakultetini tugatgan(1914).Aynan ushbu o‘quv yurtlarini keyinchalik Rossiyadagi Muvaqqat hukumatning Bosh vaziri bo‘lgan Aleksandr Kerenskiy(1881 – 1970) ham taxminan o‘n yil oldin 1899 va 1904 yillarda tugatgan edi.Mustafo Cho‘qay 1916 – 1917 yillarda Rossiya IV Davlat dumasining musulmonlar fraksiyasida kotib va tarjimon bo‘lib ishlaydi.Turkistonda 1916 yili ko‘tarilgan qo‘zg‘olon shafqatsiz bostirilgandan keyin Davlat dumasining A.Kerenskiy boshchilik qilgan maxsus komissiyasi tarkibida o‘sha yili avgust oyida Turkiston o‘lkasida, jumladan, Jizzaxda bo‘lib vayronaga aylangan shahar xarobalarini ko‘rgan.\n" +
                "1917 yil aprelda Mustafo Cho‘qay Petrograddan Toshkentga qaytdi va Turkistondagi siyosiy jarayonlar markazida turdi.U Toshkentda 1917 yil bahoridan boshlab “Birlik tug‘i” va «Svobodnыy Turkestan» gazetalarini chop eta boshladi. 1917 yil 16 – 23 aprelda Toshkentda o‘tgan Butunturkiston musulmonlarining I qurultoyida Mustafo Cho‘qay raisligida Turkiston o‘lka musulmonlari Markaziy Sho‘rosi [Kraymussovet], ya’ni Milliy Markaz tashkil qilindi.Orenburgda 21 – 28 iyulda o‘tgan Butunqirg‘iz [Butunqozoq] I s’yezdida faol qatnashdi.Muvaqqat hukumatning Turkiston Komiteti a’zosi(1917 yil avgustdan).Toshkentda bolsheviklar tomonidan zo‘ravonlik bilan hokimiyat bosib olingach, Mustafo Cho‘qay boshchiligidagi Milliy Markaz noyabr oyi boshlarida Qo‘qonga ko‘chib bordi[4].\n" +
                "1917 yil 26-28 noyabrda(yangi hisob bilan 9- 11 dekabrda) Qo‘qon shahrida Butunturkiston musulmonlarining favqulodda IV qurultoyi bo‘lib o‘tdi.Bu qurultoyni o‘lka musulmonlari Markaziy Sho‘rosi(Kraymussovet) raisi Mustafo Cho‘qay kirish so‘zi bilan ochib berdi.U qurultoy hay’ati a’zoligiga ham saylandi.Qurultoy qatnashchilari uch kun davomida Turkiston o‘lkasining bo‘lg‘usi siyosiy tuzilishi haqidagi o‘z qarashlarini belgilab olishdi.Qurultoy qarorlarini ishlab chiqishda Mustafo Cho‘qay bilan birgalikda Muhammadjon Tinishboyev, Islom Sulton Shoaxmedov, Ubaydulla Xo‘jayev, Obidjon Mahmudov, Mahmudxo‘ja Behbudiy va boshqalar muhim rol o‘ynashdi.\n" +

                "Turkiston Muxtoriyati hukumati dastlab 8 nafar kishidan iborat tarkibda tuzildi.Muhammadjon Tinishboyev Bosh vazir va ichki ishlar vaziri lavozimini egalladi.Mustafo Cho‘qay tashqi ishlar vaziri lavozimiga saylandi.Hukumat tarkibiga Ubaydulla Xo‘jayev harbiy vazir va Obidjon Mahmudov oziq - ovqat vaziri sifatida kiritildi.Qurultoyda saylangan Turkiston Milliy Majlisi tarkibiga ko‘pchilik qatori Mustafo Cho‘qay ham kiritildi.\n" +
                "1917 yil 12 dekabrdan boshlab Mustafo Cho‘qay Turkiston Muxtoriyati hukumatining Bosh vaziri bo‘ldi. (M.Tinishboyev Alash O‘rda avtonom hukumati faoliyatida bevosita qatnashish uchun Qo‘qondan Orenburgga jo‘nab ketgan edi.) Ayni paytda Mustafo Cho‘qay Orenburgda 1917 yil 5 - 13 dekabrda(yangi hisob bilan 18 - 26 dekabrda) bo‘lib o‘tgan Butunqirg‘iz[Butunqozoq] vakillarining I s’yezdida tashkil qilingan Alash O‘rda hukumatining ham tashqi ishlar vaziri bo‘lgan.\n" +
                "Shu o‘rinda Mustafo Cho‘qayning Alash O‘rda avtonom hukumati va rahbariyatiga bo‘lgan munosabatini aytib o‘tish lozim.Yoshligidan turkchilik g‘oyalari bilan tarbiyalangan Mustafo Cho‘qay yagona va bo‘linmas Turkiston tuzish tarafdori edi.U qozoq elatdoshlari bo‘lgan “Alash” partiyasi a’zolariga alohida avtonom hukumat tuzish zarur emasligini, ular yangi tashkil qilingan Turkiston Muxtoriyati hukumati tarkibiga alohida viloyat sifatida kirishlari mumkinligini bildiradi.Kelajakda bu muxtoriyatga Buxoro amirligi va Xiva xonligi hududlarini ham qo‘shib olgan holda mustaqil Turkiston davlatini(O‘zbekiston yoki Qozog‘iston emas!) tuzish imkoniyati vujudga kelar edi.Biroq Mustafo Cho‘qay, Behbudiy, Munavvar Qori, Ubaydulla Xo‘jayev, Fayzulla Xo‘jayev kabi millat yetakchilarining bunday geosiyosiy qarashlari qozoq bovurlarimizga yoqmaydi.Shuning uchun Mustafo Cho‘qay o‘zi Alash O‘rda hukumati a’zosi va qozoq bo‘la turib, keyinchalik Qo‘qondagi fojialardan so‘ng ham haqli ravishda Alash O‘rda hukumatida faoliyat ko‘rsatmaydi va Orenburgda o‘rnashgan alasho‘rdachilar bilan aloqaga chiqmaydi.\n" +

                "Muxtoriyat hukumati bolsheviklarning harbiy kuchlari tomonidan tugatilgach, 1918 yil fevral oxirida Qo‘qondan chiqib ketdi hamda yashirin ravishda mart oyida Toshkentga keldi va bu yerda 2 oy yashadi.U 1918 yil 16 aprelda eski tanishi aktrisa Mariya Yakovlevna Gorina(1888 – 1969) bilan Toshkentdagi masjidda nikohdan o‘tib, turmush quradi.Yosh oila 1918 yil 1 mayda Toshkentdan poyezdda Moskvaga jo‘naydi.Biroq poyezd Volgadagi jangovar harakatlar sababli Aktyubinskkacha boradi, xolos. 1918 yil 8 iyunda Samarada bolsheviklarga qarshi Ta’sis majlisi a’zolari komiteti(Komuch) hukumati tuzildi.Iyul oyida Alash O‘rda rahbarlari Alixon Bukeyxanov va Mustafo Cho‘qay Samaraga kelib, Komuch hukumati bilan bolsheviklarga qarshi harbiy - siyosiy ittifoq tuzdi.Bu paytda Mustafo Cho‘qay Samara, Ufa, Omskda faoliyat ko‘rsatdi. 1918 yil 18 noyabrda o‘z safdoshlari bilan qamoqqa olingan Mustafo Cho‘qay turkistonlik eser Vadim Chaykin va tatar Ilyos Alkin bilan Chelyabinskda qamoqdan qochadi. 1918 yil 1 dekabrda Orenburgdagi Karvonsaroyda(Boshqirdiston hukumati qarorgohida) u bilan Boshqirdiston hukumati raisi Ahmad Zaki Validiy o‘rtasida uchrashuv bo‘ldi.Mustafo Cho‘qay qisqa muddat Komuch hukumatida faoliyat ko‘rsatdi.\n" + "Mustafo Cho‘qay 1919 yil fevralda Yevropa davlatlariga maxsus memorandum bilan murojaat qilib, Turkistondagi istiqlolchilarning bolsheviklarga qarshi kurashini qo‘llab - quvvatlashga, sovet rejimini ag‘darib tashlashga chaqirdi.\n" +

                "Mustafo Cho‘qay qozoq dashtlari va Kaspiy dengizi orqali 1919 yil bahorida avval Boku so‘ngra Tiflis[Tbilisi] shahriga boradi.U Tiflisda 2 yil yashaydi.Bu yerda u musulmonlar uchun “Yeni Dünya” va “Şafak” gazetalarini tashkil qilib, “Na rubeje” jurnaliga muharrirlik qildi.Qizil armiya Tiflisni bosib olgach, 1921 yil fevral oyida Mustafo Cho‘qay muhojirlikka jo‘nab ketishga majbur bo‘ldi hamda Istanbulga yetib keldi.Mustafo Cho‘qay xotini bilan 1921 yil yozida Parijga keldi.Mustafo Cho‘qay muhojirlikda 20 yil yashab, turli xalqaro anjumanlarda ishtirok etdi hamda matbuotda ingliz, fransuz, polyak, rus, turk tillarida o‘tkir publisistik maqolalar bilan muntazam qatnashib turdi.Parijda uning rus tilida “Markaziy Osiyodagi Sovetlar” (1928) hamda “Turkiston sovet hokimiyati ostida” (1935) hamda turk tilida Parij – Berlinda “1917 yil xotiralari parchalari” (1937) kitoblari nashr etildi.\n" +

                "Mustafo Cho‘qay 1929 yildan boshlab Turkiston Milliy Birligi Markaziy Qo‘mitasining raisi bo‘ldi. 1929 – 1939 yillarda chiqqan “Yaş Türkistan” jurnaliga muharrirlik qildi.Jurnal Parijda tayyorlanib, Berlinda chop etilgan(uning 117 ta nomeri chop etilgan). Mustafo Cho‘qay xorijda muhojirlikda yashayotganda O‘rta Osiyo respublikalarida sovet rejimiga qarshi davom etayotgan qurolli istiqlolchilik harakati(sovet hokimiyati yillarida u “bosmachilik” harakati deb atalgan) to‘g‘risida 1930 yil 19 fevralda “O basmachestve” maqolasida shunday deb yozgan edi: “Turkiston – Sovet Ittifoqining qo‘zg‘olonchilar hozirgacha o‘z harakatini to‘xtatmagan yagona qismi.Buning ikkita sababi bor.Birinchidan, Moskva zulmidan qutulish uchun mamlakatni kurashga olib kelgan milliy tuyg‘uning kuchliligi.Bu umumiy holatning sababi hisoblanadi.Ikkinchidan, mahalliy xususiyatga molik sabab ham bor.Bu sovet milliy siyosatining faqat Turkistonga xos alohida xususiyatidir...\n" +

                "        Turkiston aholisi sovet hokimiyatiga qarshi uzluksiz(permanent) kurash holatidadir.Sovet hokimiyatiga qarshi “permanent kurash” kayfiyati zaminida qaytadan bosmachilikning paydo bo‘lishi bizni hayron qoldirmaydi.Bosmachilik - Turkistonda sovet xo‘jayinchiligining ko‘lankasi.\n" + "Bosmachilik  aynan Farg‘onada yuz berganligi shuni yaqqol ko‘rsatadiki, bu holat Moskva hukumatining paxta siyosatiga qarshi tez orada qo‘zg‘olonchilik harakati boshlanishiga ham sabab bo‘ladi”.\n" +

                "Germaniya SSSRga hujum qilgan 1941 yil 22 iyun kuni nasistlar Parij atrofidagi Nojan shaharchasida yashayotgan Mustafo Cho‘qayni qamoqqa olishdi hamda u 13 iyulgacha Kompyen xarbiy lagerida tutqunlikda saqlandi[8].So‘ngra Mustafo Cho‘qay Berlinda bo‘ldi(15 iyuldan 26 avgustgacha).U 1941 yil sentyabr – dekabr oylarida sovet harbiy asirlari saqlanayotgan Suvalki, Vustrau va Chenstoxova konslagerlarida bo‘lib, asir olingan turkistonliklarni omon saqlash yo‘llarini izladi.Mustafo Cho‘qay va toshkentlik o‘zbek Vali Qayumxon(1904 – 1993) asir olingan turkistonliklardan Turkiston legioni tuzishni rejalashtirdilar.Biroq Mustafo Cho‘qay konslagerlarda yuqumli kasallikka chalindi hamda Berlindagi “Viktoriya” kasalxonasida tepkili terlama(tif)dan 1941 yil 27 dekabrda vafot etdi.U Berlindagi turk musulmonlarining Tempelxof qabristonida 1942 yil 2 yanvarda dafn etildi.\n" +

                "Mustafo Cho‘qay rus, o‘zbek, qozoq, turk, fransuz, ingliz, nemis, polyak tillarida Turkistonning XX asr tarixiga oid ko‘plab maqolalar va kitoblar yozdi. “1917 yil xotira parchalari” (Berlin, 1937; o‘zbek tilida) kitobi katta shuhrat qozondi.Bu asar turk(Anqara, 1988), rus(Germaniya, 1989; Tokio - Moskva, 2001), o‘zbek(Toshkent, 1992) tillarida alohida kitob bo‘lib nashr qilindi.Uning 2 jildli “Tanlangan asarlar” kitobi(Almati, 1998 - 1999) qozoq va qisman rus tillarida bosilib chiqdi.\n" +
                "SSSR tarqalgach, Qozog‘iston va O‘zbekistonda Mustafo Cho‘qayning asarlari chop etildi.Taniqli tarixchi olim professor Kushim Yesmag‘ambetov(1938 – 2016) boshchiligida 2012 – 2014 yillarda Almatida Mustafo Cho‘qayning 12 jildlik asarlar to‘plami nashrdan chiqdi.Qozog‘istonda Mustafo Cho‘qay haqida badiiy asarlar yaratildi, kinofilmlar suratga olindi, uning xotirasiga atab ko‘plab haykallari o‘rnatildi.Bu yerda muntazam ravishda Mustafo Cho‘qayga bag‘ishlangan xalqaro konferensiyalar o‘tkazib turiladi.\n" +

                "Shunday qilib, turkiy xalqlarning atoqli farzandi, mashhar davlat va siyosiy davlat arbobi Mustafo Cho‘qayning hayoti va faoliyati XXI asrda yashayotgan barcha turkiy xalqlar, xususan, qozoqlar va o‘zbeklar uchun porloq namuna hisoblanadi.O‘z hayotini Turkiston birligi va mustaqilligi uchun kurashga bag‘ishlagan, ham Rossiya imperiyasi, ham sovet davlati, ham Yevropada muhojirlikda, ham Germaniyada nasistlar hukmronligi sharoitida murakkab va ziddiyatli bir vaziyatda faoliyat yuritgan bo‘lishiga qaramasdan u yorqin siymo bo‘lib qolaveradi.\n"
        },
        {
            img: man6, text: "Islom Sulton Shoahmedov", dob: "1882-1937-yillar", about: "Taniqli musulmon jamoat va siyosat arbobi. 1882-yil 21-noyabrda Orenburgda tatar-boshqird oilasida tugʻilgan. Otasi – Shagisulton (Sulton) Shagiaxmetovich Shagiaxmetov (1855-1896) Ufa guberniyasi Menzalinsk uyezdidagi boshqirdlar urugʻidan boʻlib, u 1876-yilda Qozon universitetining yuridik fakultetini tugatgan. U 1876-1890-yillarda Orenburg tatar muallimlari maktabida oʻqituvchilik qilgan, soʻngra Orenburg oʻlkasidagi sud idoralarida tergovchi boʻlib ishlagan.\n"
                + "Onasi – Gaynizigan Muhammad- Sodiqovna Nigmatullina tatar ayoli boʻlib, u kelib chiqishi jihatidan oqsuyaklar tabaqasiga mansub boʻlgan.I.Shoaxmedovning dunyoqarashi asosan Orenburg tatarlari oʻrtasida shakllangan.Uning maʼnaviy hayoti va ijtimoiy qarashlari shakllanishida tatar ayoli boʻlgan onasi muhim rol oʻynagan.\n" +

                "                I.Shoaxmedov Orenburg erkaklar gimnaziyasini tugatgach(1905), Sankt - Peterburg universitetining avval sharqshunoslik, soʻngra yuridik fakultetida oʻqiydi(1905 – 1910).Turkiy va rus tillaridan tashqari ingliz, fransuz, nemis tillarini yaxshi bilgan.Talabalik paytida u Rossiyadagi sotsial - demokratik harakatga qiziqib, 1907 - yilda Toshkent garnizoni soldatlari oʻrtasida tashviqot ishlarini olib borgan.\n" +
                "Universitetning toʻliq kursini 1910 - yil oxirida tugatib, 1911 - yil yanvarda u diplomni olgan.Sankt - Peterburg sud palatasida 1912 - yil avgustdan ish boshlaydi.U Peterburgda 1912 - yil oktyabrda chiqqan “Musulmanskoy gazetы”ning muharriri boʻldi.Bir qator sud ishlarida mensheviklar partiyasi vakillarini himoya qiladi.I.Shoaxmedov Rossiya imperiyasidagi musulmon aholisi huquqlari uchun kurashgan. 1915 - yil boshlarida Qoʻqonga kelgan.I.Shoaxmedov Skobelev okrug sudida tergovchi advokat oʻrinbosari sifatida oʻz faoliyatini boshlaydi.Bu yerda u “Sadoi Fargʻona” gazetasini chiqarishda muhim rol oʻynaydi. 1916 - yilda u “Gʻayrat” jamiyatini tuzib, “Turkestanskiy kray” gazetasi nashrini yoʻlga qoʻyadi va unga muharrirlik qiladi. 1916 - yil Fargʻona vodiysida koʻtarilgan mardikorchilik qoʻzgʻolonini qoʻllab - quvvatlaydi.\n" +
                "Fevral inqilobi kunlarida u Petrogradda boʻlgan.Bu paytda Xalq sotsialistlari partiyasiga yaqinlashgan. 1917 - yil mart oyi oxirida u Turkistonga qaytadi. 1917 - yil iyundan boshlab Milliy Shoʻro Ijroiya komiteti raisi vazifasini bajaruvchi boʻlib faoliyat koʻrsatgan.Qozonda 1917 - yilda oʻtkazilgan Butunrossiya musulmonlari II syezdi qatnashchisi.\n" +
                "            Shoaxmedov 1917 - yil Toshkentga kelib, Turkistondagi muxtoriyatchilik harakatida faol qatnashdi.Qayta chiqa boshlagan “Turkestanskiy kray” (Toshkent, 1917) gazetasi muharriri va noshiri.Turkiston musulmonlari Markaziy Shoʻrosi aʼzosi.Butunturkiston musulmonlari I - IV qurultoylarining faol qatnashchisi.\n" +
                "Turkiston Muxtoriyati hukumatida Bosh vazir oʻrinbosari, keyinchalik moliya vaziri boʻldi.Turkiston Muxtoriyati Konstitutsiyasi loyihasining muallifi.Muxtoriyat hukumati tugatilgan paytda Qoʻqon qoʻrgʻoni ichida bolsheviklar tomonidan qoʻlga olingan(1918 - yil fevral)\n" +
                "“Ulugʻ Turkiston” gazetasida 1918 - yil bahorida yozilishicha, u Toshkentdagi qamoqxonada qiynoqlar natijasida aqldan ozgan va turma lazaretiga koʻchirilgan. 1918 - yil may oyida bolsheviklar tomonidan Turkiston Muxtoriyati hukumatining tirik qolgan aʼzolari amnistiya qilingach, qamoqdan chiqqan.\n" +
                "1919 - 1920 - yillarda I.Shoaxmedov bolsheviklar bilan hamkorlik qilgan.U Turkiston Xalq Xoʻjaligi Markaziy Kengashi hamda Qoʻqon uyezd - shahar revkomida 1920 - yili faoliyat koʻrsatgan. 1920 - yil oxirida u yashirin ravishda Manjuriyaga joʻnab ketgan. 1921 - yil boshlarida u Britaniya Hindistoniga qarashli Peshovardagi rus qochoqlari joylashgan lagerga tushib qolgan.\n" +
                "1921 - yil may oyida qattiq kasal boʻlib yotgan I.Shoaxmedovning xati Parijdagi rus muhojirlari qoʻliga kelib tushadi.Bu haqda keyinchalik Mustafo Choʻqay ham oʻz maqolasida yozib oʻtadi.I.Shoaxmedov qarindoshi badavlat savdogar Agafurov oilasining moddiy koʻmagida 1921 - yil avgustda Vladivostokka keladi.U bu yerdan Parijga joʻnab ketishni rejalashtirgan edi.Ayrim maʼlumotlarga qaraganda, I.Shoaxmedov oradan koʻp oʻtmay qattiq kasallangan va Vladivostokdagi qarindoshlari huzuriga qolib ketgan.U taxminan 1922 - yil yoki undan keyin vafot etgan.\n" +
                "Mustafo Choʻqay tomonidan 1931 - yilda Berlinda chiqarilgan “Yash Turkestan” jurnalida chiqqan “Shax - Islam Shax - Axmad - Bey” nomli maqolada yozilishicha, u 1922 - yili Parijda Shoaxmedovning singlisi bilan koʻrishgan paytda uning safdoshi ogʻir kasal boʻlgan.Shoaxmedovning keyingi taqdiri va qismatidan ular xabar topa olmagan.\n" +
                " I.Shoaxmedovning Shaxgali(1882 -?) ismli akasi(u ham yurist) hamda Bibi Maryam, Bibi Galiya, Bibi Soliya, Bibi Zuhra nomli 4 nafar singlisi boʻlgan.I.Shoaxmedovning rafiqasi: Olga Viktorovna Benedskaya(1909 - yildan)."
        },
        {
            img: man5, text: "Ubaydulla Xo‘jayev", dob: "1878-1942-yillar", about: "Ubaydulla Xo‘jayev [Ubaydullaxo‘ja Asadullaxo‘jayev; Ubaydulla Asaddullayevich Xo‘jayev] – taniqli davlat va jamoat arbobi, Turkistondagi jadidchilik harakatining taniqli namoyandasi, o‘zbek matbuotining tashkilotchilaridan biri.\n" +

                "Toshkent shahrida hunarmand oilasida 1886 yili tug‘ilgan. Ba’zi manbalarda u 1878 yil 12 mayda tug‘ilgan deb ham ko‘rsatiladi. Saratovdagi huquqshunoslik institutida o‘qigan (1908 – 1912). Talabalik yillaridayoq davr muammolarini yechishni o‘ylab, mashhur rus yozuvchisi Lev Tolstoy bilan yozishmalar olib bordi (1909). Toshkent okrug sudida 1913 yildan xususiy advokat bo‘lib ishladi. Jadidchilik harakatiga qo‘shilib, tez orada uning rahbarlaridan biriga aylandi. “Turon” jamiyatining asoschilaridan biri (1913). U Toshkentda 1914 yil aprelda “Sadoi Turkiston” gazetasini chiqarib, unga muharrirlik qildi. O‘z atrofiga yoshlarni to‘plab, “Umid” yashirin jamiyatini tuzdi. Keyinchalik bu tashkilot “Taraqqiyparvar” deb nomlanib Turkiston jadidlarining asosiy tashkilotlaridan biriga aylandi. “Sadoi Turkiston” gazetasi 1915 yil aprelda Rossiya imperiyasining mahalliy ma’murlari tomonidan yopilgach, u Andijonga keldi va rus tilida “Turkestanskiy golos” gazetasini nashr qildirdi.\n" +
                "Toshkentda tuzilgan “Turkiston mardikorlikka olish qo‘mitasi”ning raisi (1916). Mardikorchilik haqidagi imperator Nikolay II farmonini bekor qildirish uchun mahalliy sarmoyador Mirkomilboy Mirmo‘minboyev bilan birga Petrogradga bordi.\n" +
                "Butunturkiston musulmonlari I qurultoyida tashkil qilingan Turkiston o‘lka musulmonlari Markaziy Sho‘rosi (Milliy Markaz) kotibi va a’zosi (1917 yil aprel). Butunrossiya musulmonlar Sho‘rosi Ijroiya Komiteti a’zosi (1917 yil may). Toshkentda 1917 yil mart oyida tuzilgan “Sho‘roi Islomiya” tashkiloti raisi. Muxtoriyatchilik harakati tashabbuskorlaridan biri. Turkiston Muxtoriyati hukumatining harbiy ishlar vaziri (1917 yil noyabr – 1918 yil fevral).\n" +
                "Ubaydulla Xo‘jayev 1918 yil fevralda hukumat topshirig‘i bilan Kavkazga bordi va Turkistonga g‘alla keltirish masalasini hal qildi. Mustafo Cho‘qayning yozishicha, muxtoriyat hukumati tugatilgach, u Ashxobod – Samarqand temir yo‘lida bolsheviklar qo‘liga tushib qoldi.\n" +

                "Sovet hokimiyati tomonidan 1918 yil mayda avf etilgach, u Orenburgga boradi va 1918 yil noyabrda Boshqirdiston Muxtoriyati hukumatini tuzishda faol ishtirok etadi.\n" +
                "Ubaydulla Xo‘jayev sovet rejimi tomonidan bir necha marta (1918, 1929, 1931, 1938) qamoqqa olingan. Toshkentda singlisining uyida muhtojlikda yashagan. Ingliz yozuvchisi J.R.Kiplingning mashhur “Maugli” asarini o‘zbekchaga tarjima qilgan. U oxirgi marta 1938 yil 20 fevralda Toshkentda hibsga olinib, SSSR NKVD maxsus kengashining qarori bilan 1939 yil 14 mayda 8 yil muddatga mehnat tuzatish lageriga hukm qilingan. U o‘sha kuni Gorkovsk temir yo‘li Kotlas stansiyasiga jazoni o‘tash uchun jo‘natilgan. U Kotlasdagi qamoqxonada 1942 yil 31 oktyabrda halok bo‘ldi. O‘limidan keyin sovet hokimiyati tomonidan oqlangan. Ubaydulla Xo‘jayev singlisining o‘g‘li, ya’ni jiyani bo‘lgan O‘zbekiston xalq yozuvchisi Shukrullo (1921-2020) “Tirik ruhlar” (1999) romanida o‘z tog‘asi Ubaydulla Xo‘jayev faoliyatini hamda “Kafansiz ko‘milganlar” (1990) xotira-qissasida qatag‘on qilingan yurtdoshlarimiz qismatini yoritgan."
        },
        {
            img: man7, text: "Obidjon Mahmudov", dob: "1878-1942-yillar", about: "Obidjon Abduxoliqovich Mahmudov [Obid chatoq] – Turkistondagi jadidchilik harakatining vakili, davlat va jamoat arbobi, yirik sarmoyador va noshir.Obidjon Mahmudov 1871-yil Margʻilonda tugʻilgan. Uning otasi Abduxoliq Abduqodirbek oʻgʻli boʻlib, Buxoro amirligida toʻpchiboshi lavozimida ishlagan. Abduxoliq Abduqodirbek oʻgʻli bir doʻstining taklifiga binoan Margʻilonga mehmonga borganida, otdan yiqilib oyogʻi singan va shifo topguniga qadar uning xonadonida yashashga majbur boʻlgan. U shu vaqtda doʻsti Mirzayunusning Robiya degan yaqin qarindoshiga uylanib, shu yerda yashab qolgan. Abduxoliq va Robiyaning farzandi Obidjon Mahmudov edi. Ularning toʻngʻich oʻgʻli Mirodil Qoʻqonning Shayxon mahallasidan uy-joy sotib olgach, Obidjon ham shu yergakoʻchib keladi. Shu yerda madrasa taʼlimini oladi. Darsdan boʻsh paytlarida moʻmchilik bilan shugʻullangan akasiga yordam berib, undan moʻmchilik hunarini, pochchasi Mirzakarim zargardan esa savdo-sotiqning sir-asrorlarini qunt bilan oʻrganDI.\n" +
                "Obidjon Mahmudov Qoʻqonga koʻchib kelib, madrasa taʼlimini oldi. U Kaspiy dengizidagi Cheleken yarim oroliga borib, neft qazib olish bilan shugʻullandi va boyib ketdi[2]. Obidjon Mahmudovning tez orada Qoʻqonning yirik boylaridan biriga aylanishi Rossiya imperiyasining maxsus politsiyasi boʻlmish – Turkiston rayon muhofaza boʻlimi tomonidan doimiy kuzatuvda boʻlishiga sabab boʻlgan. Obidjon  Mahmudov  1897-1901-yillarda  Sankt-Peterburg universitetining togʻ-kon muhandisligi fakultetini tugatgan. U  togʻ-kon boʻyicha yirik mutaxassis boʻlib, keyinchalik davlat arbobi, oʻzbek hamda rus tillarida ijod etgan adib, arab, turk tillarining bilimdoni, iqtisod, geologiya fanlari sohasida oʻziga xos bilimga ega boʻlgan yetuk shaxs boʻlib yetishadi..\n" +

                "Qoʻqonga qaytgach, togʻ- kon sanoati bilan shugʻullanib, Fargʻona vodiysida koʻplab neft konlarini ochishda ishtirok etdi.Shoʻrsuvdagi oltingugurt konini sotib olgan.Oʻqishni bitirganidan soʻng Qoʻqonga qaytib, neft konlarida ish boshlaydi.Karmana, Shoʻrsuv, Sariqqoʻrgʻon, Polvontosh, Olamushuk, Mumkonsoy kabi hududlardagi konlarda faoliyat olib borib, 1905 - yilda hukumat tomonidan neft va ozokerit 23 ishlanmalarini oʻrganish uchun Ozarbayjonga yuboriladi.U yerda tajriba orttirib qaytganidan soʻng, barcha konlarda neft qazib chiqarish bilan shugʻullanad.\n" +

                "Tarixchi N.Komilovning fikricha, O.Mahmudov boshchiligidagi bir guruh sarmoyadorlar 1906 - yil 15 - noyabrda Qoʻqon birja jamiyatini tashkil etishgan. 1907 - yil 9 - yanvarda birja jamiyati raisi A.I.Vegel va Obidjon Mahmudov boshchiligidagi 60 nafar aʼzo Fargʻona viloyati harbiy gubernatori Pokotilo Vasiliy Ivanovich(10.12.1904 –  28.07.1907)dan Qoʻqon birja jamiyatini tashkil etish toʻgʻrisida ruxsat soʻrashgan.\n" +
                "Jamiyatning 60 nafardan iborat aʼzosi 1906 - yil 15 - noyabrda Qoʻqon shahrida yigʻilib, Qoʻqon birja jamiyatni tashkil etish toʻgʻrisidagi qarorni koʻrib chiqishadi.Ushbu yigʻilishda birja jamiyatining Nizomi ishlab chiqilib, aʼzolik badallari ham kiritiladi.Jamiyat aʼzolari 1907 - yil 2 - yanvar kuni ham yigʻilishib, Nizomning 46 - bandiga koʻra jamiyat aʼzolarining 2 / 3 qismi birja jamiyatini tashkil etish uchun ovoz berganini eʼlon qilishadi[5].Keyinchalik 1907 - yilda 2299 - sonli xat bilan Fargʻona viloyati harbiy gubernatori Rossiya imperatori Nikolay II nomiga xat yoʻllab, birja jamiyati tuzilganligi toʻgʻrisida hisobot beradi.Qolaversa, birja jamiyati faoliyati uchun Nizom ishlab chiqilgan boʻlib, uni tayyorlashda O.Mahmudovning hissasi katta boʻlgan.Xususan, u rus boylaridan I.Larin, A.Smirnov, R.Ribakov, A.Uvalyev, A.Korotkovlar, shuningdek, oʻzbek filantroplaridan A.Samandarov, I.Qosimbekov, Mulla Bobojon Sharifboyev, Mulla Sulaymonqul kabi yaqin doʻstlari bilan bu ishga bosh - qosh boʻlgan.Ushbu nizomda jamiyatning maqsad va vazifalari, ochiq birja savdolarini oʻtkazish, Turkistonga kirib kelayotgan mahsulotlarning yagona narxini belgilash, narxlarni suniy oshishiga yoʻl qoʻymaslik kabi masalalar koʻrsatilgan.\n" +
                "Nizomga muvofiq birja jamiyati quyidagi asosiy prinsiplar asosida ishlashi belgilangan edi: 1) birja savdolarining ochiqligi va oshkoraligi; 2) birja savdolarida narxlarni shakllantirish erkinligi; 3) birja bitimlarining ixtiyoriyligi; 4) birja barcha aʼzolarining birja savdolarida ishtirok etishida oʻzaro tengligi; 5) faqat oldindan belgilangan joyda va birjada bitimlar tuzish.\n" +
                "Yuqoridagi prinsiplar asosida jamiyatning mahalliy millatga mansub vakillari birja savdolarida ruslarning noqonuniy harakatlarini tartibga solib turishgan.Qolaversa, iqtisodiy nuqtayi nazardan Turkistonda tashkil etilishi lozim boʻlgan muxtoriyatning iqtisodiy asoslarini barpo etishgan.\n" +
                "Obidjon Mahmudovning faoliyatida asosiy yoʻnalishlardan biri bu noshirchilik edi.U bu sohada ham juda koʻp ishlarni amalga oshirganligini alohida taʼkidlash lozim. 1913 - yili Obidjon Mahmudovning Fargʻona oblasti gubernatori A.I.Gippiusga murojaatiga koʻra, 5685 - sonli guvohnoma bilan gazeta faoliyatiga ruxsat berilgan.Hujjatda keltirilishicha, 1906 - yil senzura va noshirlik toʻgʻrisidagi Nizomning 114 - moddasi asosida ― “Nashri Obidjan” deb nomlangan mahalliy gazetani Qoʻqon shahrida haftasiga 3 - marta chop etish mumkinligi koʻrsatilgan.Gazetaning eʼlonlar, agentlik telegrammalari, boshqa gazetalardan xabarlarni qayta chop etish, tijorat va sanoat maʼlumotlari, yangiliklar va kashfiyotlar, voqea - hodisalar, hukumat buyruqlari va eʼlonlari asosida nashr etishga ruxsat berilgan.Gazeta faoliyatiga noshir va masʼul muharrir Obidjon Mahmudovning oʻzi edi.Gazeta oʻz faoliyatini yoʻlga qoʻygach, 1914 - yil 1 - avgustda Obidjon Mahmudov yana bir bor harbiy gubernatorga iltimosnoma yuboradi.Unda Evropa davlatlarining tinchlik va osoyishtalikni buzish borasidagi siyosati Buyuk Rossiyaning ularni daf qilish istagi bilan yagona qudratli oqimga, yakdil fikrga birlashganligi, bunday tarixiy davrda matbuot xizmati va uning vazifalari davlatning tinch - osoyishta paytlariga qaraganda yanada masʼuliyatli va murakkabroq hisoblanishi, xabarlar oqimi juda tez kelayotganligi, matbuot vazifalarini toʻliq bajarish, shuningdek, urush davri voqealari bilan ortgan jamoatchilik talablarini qondirish uchun rus tilida ― “Ferganskoye exo” va oʻzbek tilda ― “Sadoi Fargʻona” gazetalarini joriy dasturga muvofiq har kunlik qilib nashr etishga ruxsat berishini iltimos qiladi.Ushbu xatga javoban Fargʻona oblasti harbiy gubernatorining buyrugʻi chiqarilib, unga koʻra Obidjon Mahmudov nashriyotiga berilgan 5685 - sonli guvohnoma bekor qilinib, yangi nomdagi ― “Sadoi Fargʻona” gazetasi chop etiladigan boʻldi.Shunday qilib, 1914 - yildan rus tilida ― “Ferganskoye exo” va oʻzbek tilda ― “Sadoi Fargʻona” gazetalarini nashr etish boshlandi.Obidjon  Mahmudov  Fargʻona vodiysidagi jadidchilik harakatida faol qatnashgan va ularni moddiy jihatdan taʼminlab turgan.Qoʻqonda 1914 - yili bosmaxona tashkil qilgan.Bundan tashqari, Obidjon Mahmudov “Tirik soʻz” (1917) gazetasining muharriri va noshiri edi.U matbuotda dolzarb masalalar bilan chiqib, Turkiston xalqini maʼrifatli boʻlishga chaqirgan, uni ozodlik uchun kurashga daʼvat etgan[6].\n" +
                "Obidjon  Mahmudov  faoliyatining asosini mamlakatning iqtisodiy mustaqillikka erishishini taʼminlash tashkil etgan.U “Sadoi Fargʻona” gazetasida Turkiston iqtisodiyotiga oid bir necha maqolalar eʼlon qilgan va ularda oʻlkaga kapitalistik iqtisodiy munosabatlarning kirib kelishi, adolatsizlik va  suiisteʼmolchiliklar  xalqning  tobora  tinka - madorini  qurita borayotganligini taʼkidlagan.Uning “Eski asrdan bir mazmun” nomli maqolasida chorizm mustabid hokimiyati oʻlkaning iqtisodiy ahvolini ogʻirlashtirib, mahalliy xalqlarning milliy qadr - qimmatini yerga urganligini afsus bilan taʼkidlaydi.\n" +
                "Shuningdek, Obidjon Mahmudov qoʻl mehnatiga asoslangan mayda ishlab chiqarish mashinalashgan sanoat ishlab chiqarish bilan raqobat qila olmasligini taʼkidlab, ish  tanazzulga  yetib  bormasidan  ishlab  chiqarishni zamonaviylashtirish lozimligini taʼkidlaydi.Zero, eski  usuldagi  iqtisodiy  mexanizmlar Turkistonning  kelajagini  belgilab  bera  olmasligini, mustamlakachi hukumatning mamlakat boyliklarini tashib ketayotganligini ich - ichidan his qilgan holda bu borada koʻplab murojaatlar qilgan.Obidjon Mahmudovning bir maqolasida mahalliy bank ochish muammosiga eʼtibor qaratilib, unda mamlakatda dehqonlarni qarzdorlikdan qutqarish, qishloq xoʻjaligini rivojlantirish uchun ularga kredit ajratish lozimligi aytilgan.Birinchidan, bu mulkdorlarning boyligini yanada oshishiga, ikkinchidan, agar bank mablagʻi faqat mahalliy boylarning sarmoyalaridan iborat boʻlsa, bankning egasi ham millatning oʻzi boʻlishini, uchinchidan dehqonlar shu kredit orqali qarzdorlikdan xalos boʻlishini taʼkidlaydi.\n" +
                "Bundan tashqari, Obidjon Mahmudov oʻz maqolalarining birida savdogarchilik, uning oʻziga xos xususiyatlari, afzalliklari toʻgʻrisida ham maʼlumotlar bergan.Uning yozishicha, ilgarigi zamonlarda savdogar ahli nufuzli tabaqa sifatida jamiyatda oʻz oʻrniga ega boʻlgan.Ular oʻz faoliyatlarini shariat belgilab bergan normalar asosida olib borganlar.Yaʼni, sharʼan harom deb sanalgan ribo – sudxoʻrlik kabi xislatlar mahalliy savdogarchilik uchun yot hodisa ekanligini taʼkidlagan.Shuningdek, Obidjon Mahmudov maqolalarining birida qogʻoz ishlab chiqarish hunarmandchiligi toʻgʻrisida ham oʻz fikrlarini bayon etgan.Milliy qogʻoz ishlab chiqarishning yoʻq boʻlib ketmasligi uchun hukumat rahbarlarini milliy hunarmandchilikning  ushbu turini  rivojlantirishga  ahamiyat berishga chaqirgan[7].\n" +
                "Shuningdek, Obidjon Mahmudovning “Sadoi Fargʻona” gazetasida eʼlon qilgan maqolalarida oʻlkada iqtisodiy munosabatlarda adolatsizlik va suiisteʼmolchiliklar hamda Yevropa bank va firmalarining asl basharasini ochib tashladi: “...Oqcha kerak boʻlsa Fargʻonaga kel va yuringlar deb bir necha kunda: 25 firma, 10 bank, 5 - 10 komissionniy konturalar ochilub, oʻn, yigirma tarafdan oqchani tortaverdilar...Bank va firmalar faqat Nizomga toʻgʻri kelturub ishlarini oʻzlari xohlaganlaricha qilub, qancha insofsizlik qila bilsalar qildilar”[8].\n" +
                "Obidjon Mahmudov oʻz maqolalarida iqtisodiy masalalardan tashqari oʻlkadagi ijtimoiy muammolarga ham qaratgan.Uning taraqqiyparvarlik gʻoyalarida dinning inson maʼnaviy kamolotidagi oʻrnini toʻgʻri tushunish, bozor munosabatlarining shakllanish  jarayonlarini  faollashtirish, taraqqiyparvar  demokratik institutlarni vujudga keltirish, oʻlkada oʻziga xos milliy rivojlanishni shakllantirish, shuningdek, noshirlik faoliyatini rivojlantirish kabi muhim tarixiy vazifalarni amalga oshirishga harakat qilgan.Bu vazifalarni amalga oshirishning muhim shartlari – islom tushunchasini yangilash, uni mutaassiblikdan tozalash, fan yutuqlari va ilgʻor texnologiyani egallash muammolarini hal etish edi[9].\n" +
                "Obidjon Mahmudov oʻzining maqolalarida ayrim – diniy ulamolarning oʻz manfaatlari yoʻlida islom mohiyatini buzib koʻrsatganliklarini tanqid qiladi va jamiyatdagi mavjud illatlar ogʻir oqibatlarga olib kelishini koʻrsatib beradi.Qolaversa, u taʼlim, iqtisod, madaniyat va umuman jamiyat hayotining barcha sohalarini isloh qilish zaruratini tushuntirishga intilgan.Uning fikrlari milliy doirada chegaralanmay, Yevropaning texnologik jihatidan Sharqqa nisbatan ancha ilgarilab ketganligini hisobga olgan holda Gʻarb sivilizatsiyasining muhim jihatlarini eʼtirof etgan.Shuningdek, uning gʻoyalarida asosiy eʼtibor butun ijtimoiy va iqtisodiy tizimni oʻzgartirish, taʼlim - tarbiyani yangilashga qaratilgan.Xususan, u yangi usuldagi maktablarni tashkil etish, gazetalar chiqarish, darslik va oʻquv qoʻllanmalarni nashr etish, iqtisodiy mustaqillik, Yevropa madaniyati yutuqlaridan foydalanishni targʻib etish orqali milliy dunyoviy taʼlimni yuzaga keltirish, maʼnaviy hayotni yangilash va boyitish, milliy oʻzlikni anglashni yuksaltirish lozimligini uqtiradi[10].\n" +
                "Milliy taraqqiyparvarlik harakatining yetakchilaridan biri sifatida qoloqlik, turgʻunlik, savodsizlik va jamiyatning boshqa mavjud kamchiliklariga qarshi kurash olib borgan Obidjon Mahmudov islohotlar orqali din va shariat asoslarini saqlab, islomni yangi sharoitlarga moslashtirishni va milliy, dunyoviy  muammolarni  hal  qilishda  Yevropa  madaniyati yutuqlaridan foydalanishni, Rossiya imperiyasi mustamlakachilik siyosatining talonchilik mohiyatini chuqur anglab, unga qarshi xayriya jamiyatlari, nashriyot muassasalari hamda yangi iqtisodiy mexanizmlar(birja, bank) asosida mamlakatni rivojlantirish, xalqni maʼrifat va ilmli qilish yoʻlida katta jasorat koʻrsatgan fidoyi shaxs edi[11]. Obidjon Mahmudovning “Sadoi Fargʻona” gazetasida turli reklamalar, fabrika va zavodlar haqida ham maʼlumotlar chop etilgan.Shuningdek, toʻy va maʼrakalar dabdaba hamda oʻzini koʻz - koʻz qilish vositasiga aylanib borayotgani, bu illatdan voz kechish kerakligi qoʻp bor taʼkidlangan va unga qarshi aniq choralar koʻrilgani ham yozilgan.Tibbiyotga oid maʼlumotlar va eʼlonlar berib borish ham gazeta faoliyatining muhim sohalaridan biri boʻlgan.Chunki odamlarning koʻpchiligi tabiblar tomonidan davolangan boʻlib, jamiyatda tibbiy madaniyat tushunchasi yetarli darajada rivojlanmagan edi.Shu sababli, gazetada xususiy shifoxona xizmatlari haqida, davolovchi shifokorlar xizmatidan foydalanish haqida ham koʻplab reklamalar berilgan[12]. Obidjon Mahmudov 1917 - yilda Qoʻqon shahar Dumasi raisi oʻrinbosari qilib saylandi[13].U  umri  davomida  Qoʻqonning  har  taraflama rivojlanishi uchun harakat qilgan va bu yoʻlda bilim, qobiliyatini ayamagan.Bu haqda Obidjon Mahmudovga zamondosh va maslakdosh boʻlgan Mustafo Choʻqay oʻzining esdaliklarida quyidagi fikrlarni aytib oʻtadi: “Obidjon Qoʻqon shahar dumasi rais oʻrinbosari etib saylanganidan soʻng, bu yerda samarali ijod qildi.U shahar obodonchiligiga daxldor hamma narsada Yangi Qoʻqon bilan Eski Qoʻqonning bir xil rivojlanishi uchun kurashdi”[14].\n" +
                "1917 - yil 14 - martda “Shoʻroi Islomiya” tashkilotining tashkil etilishi muxtoriyat tuzish yoʻlida dastlabki qadamlardan edi.Obidjon Mahmudov tashkilot faoliyatini olib borishda va uni rivojlantirishga katta hissa qoʻshdi. “Shoʻroi Islomiya” tashkiloti va uning faoliyati haqida Obidjon Mahmudov 1926 - yil 21 - aprelda qamoqqa olinishi paytidagi soʻroq bayonnomasida batafsil koʻrsatma bergan.Bu tashkilot gʻoyalari Turkistonga, xususan, Fargʻonaga tatar maʼrifatparvari Galimjon Borudiy tomonidan olib kelingan. 1917 - yil 25 - mayda Qoʻqonda Fargʻona viloyati musulmonlari qurultoyi boʻlib oʻtadi.Qurultoy rayosatiga O.Mahmudov, S.Akayev, K.Raxmonberdiyev, T.Norboʻtabekov, A.Ziyoyev, Ya.Yaxyoxonov, A.Umarboyevlar saylanadilar.Obidjon Mahmudov boshchiligidagi jadidlar xalqni “Shoʻroi Islomiya” atrofida birlashishga chaqiradilar. 1917 - yil 12 - 14 - iyulda Skobelev shahrida viloyat musulmonlari tashkilotlarining qurultoyi boʻlib oʻtgan.Unda “Turk adami markaziyat firqasi” tashkil  etilgan.Yigʻilishda  firqa(partiya)ning  Dasturi(maromnomasi) va Nizomi qabul qilingan boʻlib, ushbu masalada Obidjon Mahmudov katta rol oʻynagan[15].Mustafo Choʻqay boshchiligidagi Milliy Markaz 1917 - yil noyabr oyi boshlarida Toshkentdan Qoʻqonga koʻchib kelgach, Obidjon Mahmudovning hovlisida joylashganlar. 1917 - yil 26 - noyabrda Turkiston oʻlkasi musulmonlarining favqulodda IV syezdida Obidjon Mahmudov 150 kishilik Qoʻqon delegatsiyasining raisi sifatida Turkiston Muxtoriyati tuzilishi uchun barcha jadidlar kabi harakat qildi, keyinchalik 13 kishidan iborat syezd hayʼatining aʼzosi sifatida esa u qurultoy aʼzoligiga viloyat, ayrim diniy hamda milliy guruhlar boʻyicha emas, balki bilimdon va ishchan kishilarni tanlash asosida kiritish lozimligini taklif etdi.Obidjon Mahmudov Turkiston Muxtoriyati tashkil etilgandan soʻng oziq - ovqat vaziri boʻlib ishladi va faoliyati davomida xalq farovonligi uchun bor kuchi, bilimi hamda aql - zakovatini ayamadi.Oʻz bosmaxonasini muxtoriyat hukumati ixtiyoriga topshirdi.Bosmaxonada Turkiston Muxtoriyati hukumatining oʻzbekcha va ruscha gazetalari chop etilgan.Turkiston Muxtoriyati Muvaqqat hukumatining  xalq  ommasiga  murojaatini  eʼlon  qilishda  Obidjon Mahmudovning roli katta boʻlgan[16].\n" +
                " Turkiston Muxtoriyati tugatilishi arafasida Obidjon Mahmudov Kavkazdan gʻalla mahsulotlari olib kelishi kerak boʻlgan.Biroq, sovet hukumati bilan qonli toʻqnashuvlar sababli Kavkazga ketolmay Buxoroda qolib ketadi[17].Sovet hokimiyati tomonidan 1918 - yil fevralda muxtoriyat hukumati tugatilgach, Mustafo Choʻqayning yozishicha, O.Mahmudov Buxoroda bolsheviklar qoʻliga tushib qoladi[18].Muxtoriyat agʻdarilgach, uning aʼzolari 3 guruhga boʻlinib ketdi, birinchisi istiqlolchilik harakati tomoniga, ikkinchisi sovetlar tarafiga va uchinchisi muhojir boʻlib xorijga ketgan.Obidjon Mahmudov esa ana shu sovetlar tarafiga vaqtinchalik oʻtishga majbur boʻlganlardan biri edi. 1918 - yil mayda Turkiston Muxtoriyati hukumati aʼzolari sovet hokimiyati tomonidan avf etilgan[19]. Obidjon Mahmudov 1918 - yil oktyabrdan – 1919 - yil may oyigacha Turkiston Avtonom Sovet Sotsialistik Respublikasi Markaziy ijroiya Qoʻmitasining Moskvadagi vakolatxonasida matbuot boʻlimi muharriri va boʻlim boshligʻi, 1919 - yil maydan – 1920 - yil aprelgacha TASSR MIQning Moskvadagi vakolatxonasida paxta ishlari boʻlimida mutaxassis, 1920 - yil aprel – 1921 - yil maygacha TASSR MIQning Moskvadagi vakolatxonasida Tashqi aloqalar boʻlimi mutaxassisi, 1921 - yil  may  –  1921 - yil  oktyabrgacha  Toshkentda(Turkkomissiya)ning axborot boʻlimida mutaxassis, 1921 - yil oktyabridan Bokuda tashkil etilgan ― Sharq xalqlari harakati va tashviqoti rayosatiga aʼzo sifatida faoliyat olib boradi. Obidjon Mahmudov Moskvada ishlashiga qaramay, Turkistonda faoliyat yuritayotgan turli tashkilotlarga rahbarlik  qildi, ularning  rivojlanishida  katta  rol  oʻynadi.U  Munavvarqori Abdurashidxonov va Sadriddinxon  Sharifxoʻjayevlar tashabbusi bilan Toshkentda tashkil etilgan “Milliy Ittihod” (“Ittihodi taraqqiy”) tashkilotining Qoʻqon shoʻbasiga boshchilik qildi.Shuningdek, Obidjon Mahmudov Anvar Poshshoning imzosi va “Mujoxidi  Islom  Anvarbey”  yozuvli  muhri  boʻlgan  instruktorlik guvohnomasiga ega boʻlib, tashkilot aʼzolariga siyosiy bilimlar bergan.\n" +
                "Obidjon Mahmudov 1921 - yili “Nashri maorif” jamiyatining tashkil etilishida ham tashabbuskorlardan boʻlgan.Turkistonlik yoshlarni Berlinga joʻnatish va kommunistik kayfiyatdan holi qilib tarbiyalash maqsadida “Nashri maorif” jamiyatining aʼzolari tarkibiga Toshkent, Buxoro, Samarqand va boshqa hududlardan hukumatning deyarli barcha aʼzolari kirgan.Jamiyat aʼzolari Berlinda oʻqiyotgan talabalar bilan xat orqali bogʻlanib turishgan.Talabalar bir necha marta oʻz xatlarida moddiy ehtiyojlarini bayon qilishgan va jamiyat aʼzolari turkistonlik talabalarga moddiy yordam koʻrsatish masalasini muhokama qilishgan.Obidjon Mahmudov 2 nafar talabani oʻz hisobidan oʻqitgan. Obidjon Mahmudov Turkistonda istiqlolchilik harakatini ham qoʻllab - quvvatlagan.Turkiston Muxtoriyati tugatilganidan soʻng, sovet hukumatiga qarshi kurashni aynan istiqlolchilar bilan birgalikda pinhona davom ettirgan, ularning ayrim uchrashuvlarini oʻz uyida tashkil etgan.Ergash qoʻrboshi, Isroilbek qoʻrboshilar bilan aloqada boʻlib, ularni moliyaviy jihatdan qoʻllab - quvvatlab turgan[20]. 1921 - yilning noyabrida Obidjon Mahmudov Turkistonda ingliz - yapon intervensiyasini tashkillash va “bosmachilar” bilan aloqa oʻrnatganlikda, noqonuniy  ishlar  bilan  shugʻullanganlikda, yashirin  yigʻilishlar uyushtirganlikda, sovetlarga  qarshi  tizimli  tashviqot  ishlari  olib borganlikda ayblanib hibsga olingan.Ammo Obidjon Mahmudov oʻz ixtiyoridagi barcha mol - mulklaridan voz kechish evaziga hibsdan ozod qilingan. Obidjon Mahmudov qamoqdan chiqqach, yana oʻz kasbi mumchilik bilan mashgʻul boʻladi.Davlat organlari lavozimlarida faoliyat koʻrsatish ilinjida 1921 - yilning dekabridan 1922 - yilning avgustiga qadar Buxoro Xalq Sovet Respublikasi Savdo - sanoat vazirligi Tashqi savdo boʻlimi xodimi sifatida xizmat qila boshlaydi.Obidjon Mahmudov 1926 - yili OGPU Kollegiyasining qaroriga muvofiq, 5 yilga qamoq jazosiga hukm qilinadi. 1926 - yil may oyida uning RSFSR MIQ raisi M.I.Kalininga yozgan xati inobatga olinib, 6 oydan soʻng barcha mol - mulklari musodara boʻlish evaziga qamoqdan ozod etiladi. Qamoqdan chiqqach, Shoʻrsuvdagi neft konida ijarachi sifatida ishlab, umrining oxirigacha oʻz sevgan kasbi bilan shugʻullanadi. 1933 - yilda Obidjon Mahmudovning Moskvada boʻlib oʻtgan Butunittifoq qishloq xoʻjalik koʻrgazmasiga Fargʻona viloyatidan topilgan togʻ qazilmalari namunalarini olib borib, koʻrgazmada togʻ - kon injeneri sifatida yana bir bor ishtirok etishi uning bizga maʼlum boʻlgan oxirgi faoliyatidan biridir.Obidjon Mahmudov 1936 - yil 21 - noyabrda endokardit kasalligi bilan vafot etadi.Marhum Qoʻqonning “Shayxon” qabristoniga dafn qilingan[21].\n" +
                "Qoʻqon jadidlarining yetakchisi, yirik maʼrifatparvar, noshir hamda geolog olim Obidjon Mahmudov ham el - yurt ravnaqi, yurt istiqboli yoʻlida xizmat qilgan.Uning taraqqiyparvarlik gʻoyalarida dinning inson maʼnaviy kamolotidagi oʻrnini toʻgʻri tushunish, bozor munosabatlarining shakllanish  jarayonlarini  faollashtirish, taraqqiyparvar  demokratik institutlarni vujudga keltirish, oʻlkada oʻziga xos milliy rivojlanishni shakllantirish, shuningdek, noshirlik faoliyatini rivojlantirish kabi muhim tarixiy vazifalarni amalga oshirishga harakat qilgan.Shuningdek, Obidjon Mahmudov xalqning turmush sharoitini yaxshilash uchun mustamlaka – feodal zulmi va ogʻir majburiyatlardan xalos boʻlish, iqtisodiy mustaqillikka erishish zarur, degan gʻoyani ilgari surdi.U oʻlka ijtimoiy hayotini yaxshi bilishi, shuningdek, odamlarni qiynayotgan muammolarni sezishi va shu yurt farzandi sifatida jamiyatda vujudga kelgan muammolarni hal qilishda jonbozlik koʻrsatgan.Turkistonda maʼrifatparvarlikning rivojlanishiga munosib hissa qoʻshgan shaxs sifatida u millatning yashashi, taraqqiy topishi uchun kurashgan taraqqiyparvar va ziyoli inson edi."

        }
    ];

    const [clones, setClones] = useState([]);
    const sliderRef = useRef(null);
    const navigate = useNavigate();
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);
    useEffect(() => {
        if (layout === "slider" && scrollType === "continuous") {
            setClones([...pics, ...pics]);
        } else {
            setClones(pics);
        }
    }, [layout, scrollType]);

    useEffect(() => {
        if (layout === "slider" && scrollType === "continuous") {
            const slider = sliderRef.current;
            let scrollInterval;

            const startScrolling = () => {
                scrollInterval = setInterval(() => {
                    if (slider) {
                        slider.scrollLeft += 1;
                        if (slider.scrollLeft >= slider.scrollWidth / 2) {
                            slider.scrollLeft = 0;
                        }
                    }
                }, 20);
            };

            startScrolling();
            return () => clearInterval(scrollInterval);
        }
    }, [clones, layout, scrollType]);

    const handleMemberClick = (index) => {
        navigate(`/member/${index}`, { state: pics[index] });
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };

    return (
        <div className="w-full pl-10 pr-10 my-5">
            <div
                className={`headings flex ${headingLayout === "row" ? "flex-row mt-10 mb-10" : "flex-col"
                    } justify-between  items-start gap-12`}
            >
                <h1 className="text-[#021321] text-5xl lg:text-6xl">{heading}</h1>
                <p className={`text-2xl  ${headingLayout === "row" ? "text-right" : "text-left"} text-[#2D2D2D] space-y-2`}>{subheading}</p>
            </div>

            <div className="relative w-full mt-5">
                {layout === "slider" ? (
                    <div
                        ref={sliderRef}
                        className="flex gap-6 mt-10 w-full overflow-x-auto whitespace-nowrap no-scrollbar"
                        style={{ scrollbarWidth: "none", msOverflowStyle: "none" }}
                    >
                        {clones.map((pic, index) => (
                            <div
                                key={index}
                                className="min-w-[250px] flex-shrink-0 cursor-pointer"
                                onClick={() => handleMemberClick(index % pics.length)}
                            >
                                <ManPicCard img={pic.img} text={pic.text} />
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="grid grid-cols-2  mb-20 md:grid-cols-4 gap-6">
                        {pics.map((pic, index) => (
                            <div
                                key={index}
                                className="cursor-pointer"
                                onClick={() => handleMemberClick(index)}
                            >
                                <ManPicCard img={pic.img} text={pic.text} />
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div >
    );
}

export default MembersSec;
